development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  password: <%= ENV.fetch["REDIS_PASSWORD"] %>
  channel_prefix: <%= ENV.fetch("ACTIONCABLE_CHANNEL_PREFIX") {"drinks"} %>